/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Clients.Klient;
import Flights.Lot;
import Reservation.Ticket;
import Resources.Lotnisko;
import Resources.Samolot;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Krzysztof
 */
public class Main extends javax.swing.JFrame {
    SYSTEM SYSTEM = new SYSTEM();
    /**
     * Creates new form Main
     */
    public Main() {
        SYSTEM.daneTEST();
        initComponents();
        StworzOsobaPanel2.setVisible(false);
        KlientWyborPanel.setVisible(false);
        StworzOsobaPanel.setVisible(false);
        StworzFirmaPanel.setVisible(false);
        RezerwacjaLotuPanel.setVisible(false);
        WgrajDanePanel.setVisible(false);
        BiletyPanel.setVisible(false);
        StworzSamolotPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        stworzKonto = new javax.swing.JButton();
        zarezerwujLot = new javax.swing.JButton();
        wgrajDane = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        KlientWyborPanel = new javax.swing.JPanel();
        wyborOsoba = new javax.swing.JButton();
        wyborFirma = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        StworzOsobaPanel = new javax.swing.JPanel();
        getImie = new java.awt.TextField();
        getNazwisko = new java.awt.TextField();
        Register = new javax.swing.JButton();
        goBack1 = new javax.swing.JButton();
        StworzFirmaPanel = new javax.swing.JPanel();
        getFirma = new java.awt.TextField();
        getKRS = new java.awt.TextField();
        Register1 = new javax.swing.JButton();
        goBack2 = new javax.swing.JButton();
        WgrajDanePanel = new javax.swing.JPanel();
        goBack3 = new javax.swing.JButton();
        selectFileButton_Lotniska = new javax.swing.JButton();
        selectFileButton_Samoloty = new javax.swing.JButton();
        selectFileButton_Klienci = new javax.swing.JButton();
        uploadButton_Klienci = new javax.swing.JButton();
        uploadButton_Samoloty = new javax.swing.JButton();
        uploadButton_Lotniska = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LotniskaText = new javax.swing.JTextField();
        SamolotyText = new javax.swing.JTextField();
        KlienciText = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ExportSamoloty = new javax.swing.JButton();
        ExportLotniska = new javax.swing.JButton();
        ExportKlienci = new javax.swing.JButton();
        RezerwacjaLotuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        klientChooser = new javax.swing.JComboBox<>();
        ZarezerwujLot = new javax.swing.JButton();
        goBack4 = new javax.swing.JButton();
        BrakMiejscText = new javax.swing.JTextField();
        BiletyPanel = new javax.swing.JPanel();
        klientChooser2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        goBack5 = new javax.swing.JButton();
        StworzSamolotPanel = new javax.swing.JPanel();
        Register2 = new javax.swing.JButton();
        goBack6 = new javax.swing.JButton();
        getKRS3 = new java.awt.TextField();
        getKRS4 = new java.awt.TextField();
        NazwaSamolotu = new java.awt.TextField();
        getKRS6 = new java.awt.TextField();
        textField1 = new java.awt.TextField();
        StworzOsobaPanel2 = new javax.swing.JPanel();
        getNazwa = new java.awt.TextField();
        getLokalizacja = new java.awt.TextField();
        Register4 = new javax.swing.JButton();
        goBack8 = new javax.swing.JButton();
        getY = new java.awt.TextField();
        getX = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMenu.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                MainMenuHierarchyChanged(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ticket Booking System");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.cyan));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setFocusable(false);

        stworzKonto.setText("Dodaj ");
        stworzKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stworzKontoActionPerformed(evt);
            }
        });

        zarezerwujLot.setText("Zarezerwuj lot");
        zarezerwujLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarezerwujLotActionPerformed(evt);
            }
        });

        wgrajDane.setText("Wgraj dane");
        wgrajDane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wgrajDaneActionPerformed(evt);
            }
        });

        jButton1.setText("Bilety klienta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
                MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainMenuLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(zarezerwujLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(stworzKonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(wgrajDane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(215, 215, 215))
        );
        MainMenuLayout.setVerticalGroup(
                MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainMenuLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stworzKonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zarezerwujLot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wgrajDane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap(227, Short.MAX_VALUE))
        );

        KlientWyborPanel.setRequestFocusEnabled(false);
        KlientWyborPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                KlientWyborPanelHierarchyChanged(evt);
            }
        });

        wyborOsoba.setText("Osoba");
        wyborOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborOsobaActionPerformed(evt);
            }
        });

        wyborFirma.setText("Firma");
        wyborFirma.setRolloverEnabled(false);
        wyborFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborFirmaActionPerformed(evt);
            }
        });

        goBack.setText("Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        jButton5.setText("Lotnisko");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Samolot");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<Klient> klienci = (ArrayList<Klient>) Klient.klienci;
            public int getSize() { return klienci.size(); }
            public String getElementAt(int i) { return klienci.get(i).getNazwa() + " " + klienci.get(i).getNazwiskoKrs(); }
        });
        jScrollPane4.setViewportView(jList4);

        jLabel4.setText(" Lista klientów ");

        jButton6.setText("Usuń");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KlientWyborPanelLayout = new javax.swing.GroupLayout(KlientWyborPanel);
        KlientWyborPanel.setLayout(KlientWyborPanelLayout);
        KlientWyborPanelLayout.setHorizontalGroup(
                KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KlientWyborPanelLayout.createSequentialGroup()
                                .addGroup(KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(KlientWyborPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KlientWyborPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(goBack)
                                                        .addComponent(wyborFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(wyborOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                                .addGroup(KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KlientWyborPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(73, 73, 73))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KlientWyborPanelLayout.createSequentialGroup()
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(79, 79, 79))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KlientWyborPanelLayout.createSequentialGroup()
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );
        KlientWyborPanelLayout.setVerticalGroup(
                KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KlientWyborPanelLayout.createSequentialGroup()
                                .addGroup(KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(KlientWyborPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 33, Short.MAX_VALUE))
                                        .addGroup(KlientWyborPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(wyborOsoba)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(wyborFirma)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2)
                                                .addGap(12, 12, 12)
                                                .addComponent(jButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );

        StworzOsobaPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                StworzOsobaPanelHierarchyChanged(evt);
            }
        });

        getImie.setText("Imie");
        getImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getImieActionPerformed(evt);
            }
        });

        getNazwisko.setText("Nazwisko");

        Register.setText("Dodaj");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        goBack1.setText("Back");
        goBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StworzOsobaPanelLayout = new javax.swing.GroupLayout(StworzOsobaPanel);
        StworzOsobaPanel.setLayout(StworzOsobaPanelLayout);
        StworzOsobaPanelLayout.setHorizontalGroup(
                StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzOsobaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(goBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getImie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                .addContainerGap(534, Short.MAX_VALUE))
        );
        StworzOsobaPanelLayout.setVerticalGroup(
                StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzOsobaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(getImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                                .addComponent(goBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        StworzFirmaPanel.setPreferredSize(new java.awt.Dimension(534, 281));
        StworzFirmaPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                StworzFirmaPanelHierarchyChanged(evt);
            }
        });

        getFirma.setText("Firma XYZ");
        getFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFirmaActionPerformed(evt);
            }
        });

        getKRS.setText("Numer KRS");

        Register1.setText("Add");
        Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register1ActionPerformed(evt);
            }
        });

        goBack2.setText("Back");
        goBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StworzFirmaPanelLayout = new javax.swing.GroupLayout(StworzFirmaPanel);
        StworzFirmaPanel.setLayout(StworzFirmaPanelLayout);
        StworzFirmaPanelLayout.setHorizontalGroup(
                StworzFirmaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StworzFirmaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(StworzFirmaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(getFirma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getKRS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Register1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StworzFirmaPanelLayout.createSequentialGroup()
                                                .addComponent(goBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(450, 450, 450))
        );
        StworzFirmaPanelLayout.setVerticalGroup(
                StworzFirmaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzFirmaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(getFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getKRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(goBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        WgrajDanePanel.setRequestFocusEnabled(false);
        WgrajDanePanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                WgrajDanePanelHierarchyChanged(evt);
            }
        });

        goBack3.setText("Back");
        goBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack3ActionPerformed(evt);
            }
        });

        selectFileButton_Lotniska.setText("Wybierz Plik");
        selectFileButton_Lotniska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButton_LotniskaActionPerformed(evt);
            }
        });

        selectFileButton_Samoloty.setText("Wybierz Plik");
        selectFileButton_Samoloty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButton_SamolotyActionPerformed(evt);
            }
        });

        selectFileButton_Klienci.setText("Wybierz Plik");
        selectFileButton_Klienci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButton_KlienciActionPerformed(evt);
            }
        });

        uploadButton_Klienci.setText("Import");
        uploadButton_Klienci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButton_KlienciActionPerformed(evt);
            }
        });

        uploadButton_Samoloty.setText("Import");
        uploadButton_Samoloty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButton_SamolotyActionPerformed(evt);
            }
        });

        uploadButton_Lotniska.setText("Import");
        uploadButton_Lotniska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButton_LotniskaActionPerformed(evt);
            }
        });

        jLabel5.setText("Lotniska");

        jLabel7.setText("Samoloty");

        jLabel8.setText("Klienci");

        LotniskaText.setText("Ścieżka do pliku");
        LotniskaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LotniskaTextActionPerformed(evt);
            }
        });

        SamolotyText.setText("Ścieżka do pliku");
        SamolotyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamolotyTextActionPerformed(evt);
            }
        });

        KlienciText.setText("Ścieżka do pliku");
        KlienciText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlienciTextActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        ExportSamoloty.setText("Export");
        ExportSamoloty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportSamolotyActionPerformed(evt);
            }
        });

        ExportLotniska.setText("Export");
        ExportLotniska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportLotniskaActionPerformed(evt);
            }
        });

        ExportKlienci.setText("Export");
        ExportKlienci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportKlienciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WgrajDanePanelLayout = new javax.swing.GroupLayout(WgrajDanePanel);
        WgrajDanePanel.setLayout(WgrajDanePanelLayout);
        WgrajDanePanelLayout.setHorizontalGroup(
                WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                                .addComponent(goBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                                                .addComponent(selectFileButton_Lotniska)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(uploadButton_Lotniska, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(selectFileButton_Klienci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(selectFileButton_Samoloty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(uploadButton_Klienci, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(uploadButton_Samoloty, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ExportKlienci, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                        .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(ExportLotniska, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(ExportSamoloty, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LotniskaText, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SamolotyText, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(KlienciText, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        WgrajDanePanelLayout.setVerticalGroup(
                WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(selectFileButton_Lotniska)
                                                        .addComponent(uploadButton_Lotniska)
                                                        .addComponent(jLabel5)
                                                        .addComponent(LotniskaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(selectFileButton_Samoloty)
                                                        .addComponent(uploadButton_Samoloty)
                                                        .addComponent(jLabel7)
                                                        .addComponent(SamolotyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ExportSamoloty))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(selectFileButton_Klienci)
                                                        .addComponent(uploadButton_Klienci)
                                                        .addComponent(jLabel8)
                                                        .addComponent(KlienciText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ExportKlienci)))
                                        .addComponent(ExportLotniska))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                                .addComponent(goBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        RezerwacjaLotuPanel.setRequestFocusEnabled(false);
        RezerwacjaLotuPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                RezerwacjaLotuPanelHierarchyChanged(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<Lot> loty = SYSTEM.getLoty();
            public int getSize() { return loty.size(); }
            public String getElementAt(int i) { return loty.get(i).toString() + "  -  " + SYSTEM.GodzinaPrzylotu(loty.get(i).GetGodzinaOdlotu(), SYSTEM.Odleglosc(loty.get(i).GetLotniskoP(),loty.get(i).GetLotniskoK()),loty.get(i).GetSamolot()); }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Miejsce wylotu");

        jLabel3.setText("Miejsce przylotu");

        Choice choice1 = new Choice();

        // Populate the Choice component with airport names
        for (Lotnisko lotnisko : SYSTEM.getLotniska()) {
            choice1.add(lotnisko.getNazwa());
        }

        // ItemListener for the Choice component
        ItemListener choiceListener111 = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedAirport = choice1.getSelectedItem();
                    // Perform any action with the selected airport
                    System.out.println("Selected airport: " + selectedAirport);
                }
            }
        };

        // Add the ItemListener to the Choice component
        choice1.addItemListener(choiceListener111);

        Choice choice2 = new Choice();

        // Populate the Choice component with airport names
        for (Lotnisko lotnisko : SYSTEM.getLotniska()) {
            choice2.add(lotnisko.getNazwa());
        }

        // ItemListener for the Choice component
        ItemListener choiceListener211 = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    String selectedAirport = choice2.getSelectedItem();
                    // Perform any action with the selected airport
                    System.out.println("Selected airport: " + selectedAirport);
                }
            }
        };

        // Add the ItemListener to the Choice component
        choice1.addItemListener(choiceListener211);

        jLabel6.setText("Pasażerowie");

        refreshButton.setText("Odśwież");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        refreshButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedChoice1 = choice1.getSelectedItem();
                String selectedChoice2 = choice2.getSelectedItem();

                ListModel<String> customModel = jList1.getModel();
                DefaultListModel<String> model = new DefaultListModel<>();

                ArrayList<Lot> loty = SYSTEM.getLoty();
                for (Lot lot : loty) {
                    if (lot.GetLotniskoP().getNazwa().equals(selectedChoice1) && lot.GetLotniskoK().getNazwa().equals(selectedChoice2)) {
                        String element = lot.toString() + "  -  " + SYSTEM.GodzinaPrzylotu(lot.GetGodzinaOdlotu(), SYSTEM.Odleglosc(lot.GetLotniskoP(),lot.GetLotniskoK()),lot.GetSamolot());
                        model.addElement(element);
                    }
                }

                jList1.setModel(model);
            }
        });

        for (Klient klient : Klient.klienci) {
            klientChooser.addItem(klient.getNazwa());
        }
        klientChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klientChooserActionPerformed(evt);
            }
        });

        ZarezerwujLot.setText("Zarezerwuj");
        ZarezerwujLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZarezerwujLotActionPerformed(evt);
            }
        });

        goBack4.setText("Back");
        goBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RezerwacjaLotuPanelLayout = new javax.swing.GroupLayout(RezerwacjaLotuPanel);
        RezerwacjaLotuPanel.setLayout(RezerwacjaLotuPanelLayout);
        RezerwacjaLotuPanelLayout.setHorizontalGroup(
                RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3)
                                                        .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                                .addGap(110, 110, 110)
                                                                .addComponent(jLabel6))
                                                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSpinner1)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(klientChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                .addComponent(goBack4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BrakMiejscText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ZarezerwujLot)))
                                .addContainerGap())
        );
        RezerwacjaLotuPanelLayout.setVerticalGroup(
                RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RezerwacjaLotuPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(klientChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(choice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(goBack4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ZarezerwujLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BrakMiejscText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        BiletyPanel.setRequestFocusEnabled(false);
        BiletyPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                BiletyPanelHierarchyChanged(evt);
            }
        });

        for (Klient klient : Klient.klienci) {
            klientChooser2.addItem(klient.getNazwa());
        }
        klientChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klientChooser2ActionPerformed(evt);
            }
        });
        klientChooser2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                DefaultListModel<String> model2 = new DefaultListModel<>();
                model2.clear(); // Clear the JList before adding new elements
                jList2.setModel(model2);

                int selectedClientIndex = klientChooser2.getSelectedIndex();
                Klient selectedKlient = Klient.klienci.get(selectedClientIndex);
                ArrayList<Ticket> bilety = (ArrayList<Ticket>) selectedKlient.bilety;

                int i = 1;
                for (Ticket bilet : bilety) {
                    if(bilet.getKlient()==selectedKlient){
                        String element = i + ". "+ bilet.getLot().toString() + "  -  " + SYSTEM.GodzinaPrzylotu(bilet.getLot().GetGodzinaOdlotu(), SYSTEM.Odleglosc(bilet.getLot().GetLotniskoP(),bilet.getLot().GetLotniskoK()),bilet.getLot().GetSamolot());
                        model2.addElement(element);
                        i++;
                    }
                }
                i = 0;
                jList2.setModel(model2);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            int selectedClientIndex = klientChooser2.getSelectedIndex();
            Klient selectedKlient = Klient.klienci.get(selectedClientIndex);
            ArrayList<Ticket> bilety = (ArrayList<Ticket>) selectedKlient.bilety;
            public int getSize() { return bilety.size(); }
            public String getElementAt(int i) { return bilety.get(i).getLot().toString() + "  -  "; }
        });
        jScrollPane2.setViewportView(jList2);

        goBack5.setText("Back");
        goBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BiletyPanelLayout = new javax.swing.GroupLayout(BiletyPanel);
        BiletyPanel.setLayout(BiletyPanelLayout);
        BiletyPanelLayout.setHorizontalGroup(
                BiletyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiletyPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(BiletyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                                        .addGroup(BiletyPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(klientChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addGroup(BiletyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BiletyPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(goBack5)
                                        .addContainerGap(537, Short.MAX_VALUE)))
        );
        BiletyPanelLayout.setVerticalGroup(
                BiletyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BiletyPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(klientChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(65, Short.MAX_VALUE))
                        .addGroup(BiletyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiletyPanelLayout.createSequentialGroup()
                                        .addContainerGap(409, Short.MAX_VALUE)
                                        .addComponent(goBack5)
                                        .addContainerGap()))
        );

        StworzSamolotPanel.setPreferredSize(new java.awt.Dimension(534, 281));
        StworzSamolotPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                StworzSamolotPanelHierarchyChanged(evt);
            }
        });

        Register2.setText("Add");
        Register2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register2ActionPerformed(evt);
            }
        });

        goBack6.setText("Back");
        goBack6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack6ActionPerformed(evt);
            }
        });

        getKRS3.setText("Zasięg");
        getKRS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getKRS3ActionPerformed(evt);
            }
        });

        getKRS4.setText("Ilość miejsc");

        NazwaSamolotu.setText("Nazwa");
        NazwaSamolotu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazwaSamolotuActionPerformed(evt);
            }
        });

        getKRS6.setText("Prędkość");

        textField1.setText("Lotnisko ");

        javax.swing.GroupLayout StworzSamolotPanelLayout = new javax.swing.GroupLayout(StworzSamolotPanel);
        StworzSamolotPanel.setLayout(StworzSamolotPanelLayout);
        StworzSamolotPanelLayout.setHorizontalGroup(
                StworzSamolotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzSamolotPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(StworzSamolotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(StworzSamolotPanelLayout.createSequentialGroup()
                                                .addGroup(StworzSamolotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(goBack6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(getKRS4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(339, Short.MAX_VALUE))
                                        .addGroup(StworzSamolotPanelLayout.createSequentialGroup()
                                                .addGroup(StworzSamolotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(NazwaSamolotu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                                        .addComponent(getKRS3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(getKRS6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                                        .addComponent(Register2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );
        StworzSamolotPanelLayout.setVerticalGroup(
                StworzSamolotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzSamolotPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NazwaSamolotu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getKRS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getKRS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getKRS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(goBack6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        StworzOsobaPanel2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                StworzOsobaPanel2HierarchyChanged(evt);
            }
        });

        getNazwa.setText("Nazwa");
        getNazwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNazwaActionPerformed(evt);
            }
        });

        getLokalizacja.setText("Lokalizacja");

        Register4.setText("Dodaj");
        Register4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register4ActionPerformed(evt);
            }
        });

        goBack8.setText("Back");
        goBack8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack8ActionPerformed(evt);
            }
        });

        getY.setText("Y");
        getY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getYActionPerformed(evt);
            }
        });

        getX.setText("X");
        getX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StworzOsobaPanel2Layout = new javax.swing.GroupLayout(StworzOsobaPanel2);
        StworzOsobaPanel2.setLayout(StworzOsobaPanel2Layout);
        StworzOsobaPanel2Layout.setHorizontalGroup(
                StworzOsobaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzOsobaPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(StworzOsobaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(getX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(goBack8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getLokalizacja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getNazwa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(Register4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(513, Short.MAX_VALUE))
        );
        StworzOsobaPanel2Layout.setVerticalGroup(
                StworzOsobaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzOsobaPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(getNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getLokalizacja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                                .addComponent(goBack8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KlientWyborPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(StworzOsobaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StworzFirmaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(RezerwacjaLotuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(WgrajDanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(BiletyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(StworzSamolotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                                        .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(StworzOsobaPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(95, 95, 95)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KlientWyborPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StworzOsobaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StworzFirmaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(RezerwacjaLotuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(WgrajDanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(BiletyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(StworzSamolotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                        .addGap(83, 83, 83)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(StworzOsobaPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(159, 159, 159)))
        );

        pack();
    }// </editor-fold>

    private void stworzKontoActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void zarezerwujLotActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu.setVisible(false);
        RezerwacjaLotuPanel.setVisible(true);
    }

    private void wgrajDaneActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu.setVisible(false);
        WgrajDanePanel.setVisible(true);
    }

    private void MainMenuHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void StworzOsobaPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void getImieActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {
        SYSTEM.StworzOsobe(getImie.getText(),getNazwisko.getText());
        klientChooser2.addItem(getImie.getText());
        klientChooser.addItem(getImie.getText());
        getImie.setText("Imie");
        getNazwisko.setText("Nazwisko");

        ListModel<String> customModel = jList4.getModel();
        DefaultListModel<String> model = new DefaultListModel<>();

        ArrayList<Klient> klienci = (ArrayList<Klient>) Klient.klienci;
        for (Klient klient : klienci) {
            model.addElement(klient.getNazwa() + " " + klient.getNazwiskoKrs());
        }

        jList4.setModel(model);
    }

    private void getFirmaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Register1ActionPerformed(java.awt.event.ActionEvent evt) {
        SYSTEM.StworzFirme(getFirma.getText(),getKRS.getText());
        klientChooser2.addItem(getFirma.getText());
        klientChooser.addItem(getFirma.getText());
        getFirma.setText("Firma XYZ");
        getKRS.setText("Numer KRS");
        ListModel<String> customModel = jList4.getModel();
        DefaultListModel<String> model = new DefaultListModel<>();

        ArrayList<Klient> klienci = (ArrayList<Klient>) Klient.klienci;
        for (Klient klient : klienci) {
            model.addElement(klient.getNazwa() + " " + klient.getNazwiskoKrs());
        }

        jList4.setModel(model);
    }

    private void StworzFirmaPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void goBack1ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzOsobaPanel.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void goBack2ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzFirmaPanel.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void RezerwacjaLotuPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void WgrajDanePanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ZarezerwujLotActionPerformed(java.awt.event.ActionEvent evt) {
        int[] selectedIndices = jList1.getSelectedIndices();
        ListModel<String> model = jList1.getModel();
        int selectedClientIndex = klientChooser.getSelectedIndex();
        Klient selectedKlient = Klient.klienci.get(selectedClientIndex);
        for (int selectedIndex : selectedIndices) {
            String selectedString = model.getElementAt(selectedIndex);
            String[] parts = selectedString.split("->");
            String lotnisko_p = parts[0].trim();

            // Extracting the lotnisko_k value
            Pattern pattern = Pattern.compile("->\\s+(.*?)\\s+\\d{2}\\.\\d{2}\\.\\d{4}\\s+\\d{2}:\\d{2}");
            Matcher matcher = pattern.matcher(selectedString);

            String lotnisko_k = "";
            if (matcher.find()) {
                lotnisko_k = matcher.group(1);
            }

            // Extracting the date and time using regular expressions
            pattern = Pattern.compile("(\\d{2}\\.\\d{2}\\.\\d{4})\\s+(\\d{2}:\\d{2})");
            matcher = pattern.matcher(selectedString);

            String data = "";
            String hour = "";

            if (matcher.find()) {
                data = matcher.group(1);
                hour = matcher.group(2);
            }
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime localTime = LocalTime.parse(hour, formatter);
            DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            LocalDate date = LocalDate.parse(data, formatter2);
            DayOfWeek dayOfWeek = date.getDayOfWeek();
            Lot lot = findLotByFlightDetails(lotnisko_p, lotnisko_k, dayOfWeek, localTime);
            if (lot.GetDostepneBilety() <= (int) jSpinner1.getValue()) {
                BrakMiejscText.setText("Brak miejsc");
            }
            else{
                BrakMiejscText.setText("Zarezerwowano");
                for (int i = 0; i < (int) jSpinner1.getValue(); i++) {
                    SYSTEM.rezerwacjaBiletu(selectedKlient, lot);
                }
            }
        }
    }
    private Lot findLotByFlightDetails(String lotnisko_p, String lotnisko_k, DayOfWeek dzien, LocalTime godzina_odlotu) {
        ArrayList<Lot> loty = SYSTEM.getLoty();
        for (Lot lot : loty) {
            if (lot.GetLotniskoP().getNazwa().equals(lotnisko_p) &&
                    lot.GetLotniskoK().getNazwa().equals(lotnisko_k) &&
                    lot.GetDzien() == dzien &&
                    lot.GetGodzinaOdlotu().equals(godzina_odlotu)) {
                return lot;
            }
        }
        return null; // No matching Lot found
    }
    private void klientChooserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void BiletyPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void klientChooser2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        BiletyPanel.setVisible(true);
        MainMenu.setVisible(false);
    }

    private void goBack3ActionPerformed(java.awt.event.ActionEvent evt) {
        WgrajDanePanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void goBack5ActionPerformed(java.awt.event.ActionEvent evt) {
        BiletyPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void goBack4ActionPerformed(java.awt.event.ActionEvent evt) {
        RezerwacjaLotuPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void KlientWyborPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {
        KlientWyborPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void wyborFirmaActionPerformed(java.awt.event.ActionEvent evt) {
        KlientWyborPanel.setVisible(false);
        StworzFirmaPanel.setVisible(true);
    }

    private void wyborOsobaActionPerformed(java.awt.event.ActionEvent evt) {
        KlientWyborPanel.setVisible(false);
        StworzOsobaPanel.setVisible(true);
    }

    private void selectFileButton_KlienciActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(Main.this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile2 = fileChooser.getSelectedFile();
            // Process the selected file (e.g., store the file path or perform operations on the file)
            KlienciText.setText(selectedFile2.getAbsolutePath());
        }
    }

    private void uploadButton_KlienciActionPerformed(java.awt.event.ActionEvent evt) {
        Klient.readFromFileKlient(Klient.klienci, KlienciText.getText());
    }

    private void uploadButton_SamolotyActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Samolot> samoloty = new ArrayList<>();
        Samolot.readFromFile(samoloty,SamolotyText.getText());
        for(Lotnisko lotnisko : SYSTEM.getLotniska()){
            for(Samolot samolot : samoloty){
                lotnisko.dodajSamolot(samolot);
            }
        }
    }

    private void uploadButton_LotniskaActionPerformed(java.awt.event.ActionEvent evt) {
        Lotnisko.readFromFile(SYSTEM.getLotniska(),LotniskaText.getText());
    }

    private void selectFileButton_SamolotyActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(Main.this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile1 = fileChooser.getSelectedFile();
            // Process the selected file (e.g., store the file path or perform operations on the file)
            SamolotyText.setText(selectedFile1.getAbsolutePath());
        }
    }

    private void selectFileButton_LotniskaActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(Main.this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            // Process the selected file (e.g., store the file path or perform operations on the file)
            LotniskaText.setText(selectedFile.getAbsolutePath());
        }
    }

    private void LotniskaTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void KlienciTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void SamolotyTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Register2ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzSamolotPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void goBack6ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzSamolotPanel.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void StworzSamolotPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void getKRS3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void NazwaSamolotuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzOsobaPanel2.setVisible(true);
        KlientWyborPanel.setVisible(false);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzSamolotPanel.setVisible(true);
        KlientWyborPanel.setVisible(false);
    }

    private void ExportLotniskaActionPerformed(java.awt.event.ActionEvent evt) {
        Lotnisko.writeToFile(SYSTEM.getLotniska(),"Lotniska.txt");
    }

    private void ExportSamolotyActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Samolot> samoloty = new ArrayList<>();
        for(Lotnisko lotnisko : SYSTEM.getLotniska()){
            for(Samolot samolot : samoloty){
                samoloty.add(samolot);
            }
        }
        Samolot.writeToFile(samoloty,"Samoloty.txt");
    }

    private void ExportKlienciActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        int[] selectedIndices = jList4.getSelectedIndices();
        for (int selectedIndex : selectedIndices){
            Klient.klienci.remove(selectedIndex);
        }
        ListModel<String> customModel = jList4.getModel();
        DefaultListModel<String> model = new DefaultListModel<>();

        ArrayList<Klient> klienci = (ArrayList<Klient>) Klient.klienci;
        for (Klient klient : klienci) {
            model.addElement(klient.getNazwa() + " " + klient.getNazwiskoKrs());
        }

        jList4.setModel(model);
    }

    private void getNazwaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Register4ActionPerformed(java.awt.event.ActionEvent evt) {
        Lotnisko lotnisko = new Lotnisko(getNazwa.getText(), getLokalizacja.getText(), Integer.parseInt(getX.getText()), Integer.parseInt(getY.getText()));
        SYSTEM.getLotniska().add(lotnisko);
    }

    private void goBack8ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzOsobaPanel2.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void StworzOsobaPanel2HierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void getYActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void getXActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel BiletyPanel;
    private javax.swing.JTextField BrakMiejscText;
    private javax.swing.JButton ExportKlienci;
    private javax.swing.JButton ExportLotniska;
    private javax.swing.JButton ExportSamoloty;
    private javax.swing.JTextField KlienciText;
    private javax.swing.JPanel KlientWyborPanel;
    private javax.swing.JTextField LotniskaText;
    private javax.swing.JPanel MainMenu;
    private java.awt.TextField NazwaSamolotu;
    private javax.swing.JButton Register;
    private javax.swing.JButton Register1;
    private javax.swing.JButton Register2;
    private javax.swing.JButton Register4;
    private javax.swing.JPanel RezerwacjaLotuPanel;
    private javax.swing.JTextField SamolotyText;
    private javax.swing.JPanel StworzFirmaPanel;
    private javax.swing.JPanel StworzOsobaPanel;
    private javax.swing.JPanel StworzOsobaPanel2;
    private javax.swing.JPanel StworzSamolotPanel;
    private javax.swing.JPanel WgrajDanePanel;
    private javax.swing.JButton ZarezerwujLot;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.TextField getFirma;
    private java.awt.TextField getImie;
    private java.awt.TextField getKRS;
    private java.awt.TextField getKRS3;
    private java.awt.TextField getKRS4;
    private java.awt.TextField getKRS6;
    private java.awt.TextField getLokalizacja;
    private java.awt.TextField getNazwa;
    private java.awt.TextField getNazwisko;
    private java.awt.TextField getX;
    private java.awt.TextField getY;
    private javax.swing.JButton goBack;
    private javax.swing.JButton goBack1;
    private javax.swing.JButton goBack2;
    private javax.swing.JButton goBack3;
    private javax.swing.JButton goBack4;
    private javax.swing.JButton goBack5;
    private javax.swing.JButton goBack6;
    private javax.swing.JButton goBack8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> klientChooser;
    private javax.swing.JComboBox<String> klientChooser2;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton selectFileButton_Klienci;
    private javax.swing.JButton selectFileButton_Lotniska;
    private javax.swing.JButton selectFileButton_Samoloty;
    private javax.swing.JButton stworzKonto;
    private java.awt.TextField textField1;
    private javax.swing.JButton uploadButton_Klienci;
    private javax.swing.JButton uploadButton_Lotniska;
    private javax.swing.JButton uploadButton_Samoloty;
    private javax.swing.JButton wgrajDane;
    private javax.swing.JButton wyborFirma;
    private javax.swing.JButton wyborOsoba;
    private javax.swing.JButton zarezerwujLot;
    // End of variables declaration
}
