/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Flights.Lot;
import Resources.Lotnisko;
import java.util.ArrayList;

/**
 *
 * @author Krzysztof
 */
public class Main extends javax.swing.JFrame {
    SYSTEM SYSTEM = new SYSTEM();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        KlientWyborPanel.setVisible(false);
        StworzOsobaPanel.setVisible(false);
        StworzFirmaPanel.setVisible(false);
        RezerwacjaLotuPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        stworzKonto = new javax.swing.JButton();
        zarezerwujLot = new javax.swing.JButton();
        wgrajDane = new javax.swing.JButton();
        KlientWyborPanel = new javax.swing.JPanel();
        wyborOsoba = new javax.swing.JButton();
        wyborFirma = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        StworzOsobaPanel = new javax.swing.JPanel();
        getImie = new java.awt.TextField();
        getNazwisko = new java.awt.TextField();
        Register = new javax.swing.JButton();
        goBack1 = new javax.swing.JButton();
        StworzFirmaPanel = new javax.swing.JPanel();
        getFirma = new java.awt.TextField();
        getKRS = new java.awt.TextField();
        Register1 = new javax.swing.JButton();
        goBack2 = new javax.swing.JButton();
        WgrajDanePanel = new javax.swing.JPanel();
        WgrajLoty = new javax.swing.JButton();
        WgrajSamoloty = new javax.swing.JButton();
        WgrajKlientów = new javax.swing.JButton();
        RezerwacjaLotuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        obieStrony = new javax.swing.JCheckBox();
        jednaStrona = new javax.swing.JCheckBox();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        D = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        D2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        gowno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMenu.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                MainMenuHierarchyChanged(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ticket Booking System");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.cyan));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setFocusable(false);

        stworzKonto.setText("Stwórz konto");
        stworzKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stworzKontoActionPerformed(evt);
            }
        });
        
        zarezerwujLot.setText("Zarezerwuj lot");
        zarezerwujLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarezerwujLotActionPerformed(evt);
            }
        });

        wgrajDane.setText("Wgraj dane");
        wgrajDane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wgrajDaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
                MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(zarezerwujLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(stworzKonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(wgrajDane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(225, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
                MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainMenuLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stworzKonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zarezerwujLot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wgrajDane)
                                .addContainerGap(206, Short.MAX_VALUE))
        );

        KlientWyborPanel.setRequestFocusEnabled(false);
        KlientWyborPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                KlientWyborPanelHierarchyChanged(evt);
            }
        });

        wyborOsoba.setText("Osoba");
        wyborOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborOsobaActionPerformed(evt);
            }
        });

        wyborFirma.setText("Firma");
        wyborFirma.setRolloverEnabled(false);
        wyborFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborFirmaActionPerformed(evt);
            }
        });

        goBack.setText("Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KlientWyborPanelLayout = new javax.swing.GroupLayout(KlientWyborPanel);
        KlientWyborPanel.setLayout(KlientWyborPanelLayout);
        KlientWyborPanelLayout.setHorizontalGroup(
                KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KlientWyborPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(wyborOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(wyborFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(goBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(518, Short.MAX_VALUE))
        );
        KlientWyborPanelLayout.setVerticalGroup(
                KlientWyborPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KlientWyborPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(wyborOsoba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wyborFirma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        StworzOsobaPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                StworzOsobaPanelHierarchyChanged(evt);
            }
        });

        getImie.setText("Imie");
        getImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getImieActionPerformed(evt);
            }
        });

        getNazwisko.setText("Nazwisko");

        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        goBack1.setText("Back");
        goBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StworzOsobaPanelLayout = new javax.swing.GroupLayout(StworzOsobaPanel);
        StworzOsobaPanel.setLayout(StworzOsobaPanelLayout);
        StworzOsobaPanelLayout.setHorizontalGroup(
                StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzOsobaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(getImie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(getNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                        .addComponent(goBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(495, Short.MAX_VALUE))
        );
        StworzOsobaPanelLayout.setVerticalGroup(
                StworzOsobaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzOsobaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(getImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(goBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        StworzFirmaPanel.setPreferredSize(new java.awt.Dimension(534, 281));
        StworzFirmaPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                StworzFirmaPanelHierarchyChanged(evt);
            }
        });

        getFirma.setText("Firma XYZ");
        getFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFirmaActionPerformed(evt);
            }
        });

        getKRS.setText("Numer KRS");

        Register1.setText("Register");
        Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register1ActionPerformed(evt);
            }
        });

        goBack2.setText("Back");
        goBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StworzFirmaPanelLayout = new javax.swing.GroupLayout(StworzFirmaPanel);
        StworzFirmaPanel.setLayout(StworzFirmaPanelLayout);
        StworzFirmaPanelLayout.setHorizontalGroup(
                StworzFirmaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StworzFirmaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(StworzFirmaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(getFirma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getKRS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Register1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StworzFirmaPanelLayout.createSequentialGroup()
                                                .addComponent(goBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap(450, Short.MAX_VALUE))
        );
        StworzFirmaPanelLayout.setVerticalGroup(
                StworzFirmaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StworzFirmaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(getFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getKRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(goBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        WgrajDanePanel.setRequestFocusEnabled(false);
        WgrajDanePanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                WgrajDanePanelHierarchyChanged(evt);
            }
        });

        WgrajLoty.setText("Lotniska");
        WgrajLoty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WgrajLotyActionPerformed(evt);
            }
        });

        WgrajSamoloty.setText("Samoloty");
        WgrajSamoloty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WgrajSamolotyActionPerformed(evt);
            }
        });

        WgrajKlientów.setText("Klienci");

        javax.swing.GroupLayout WgrajDanePanelLayout = new javax.swing.GroupLayout(WgrajDanePanel);
        WgrajDanePanel.setLayout(WgrajDanePanelLayout);
        WgrajDanePanelLayout.setHorizontalGroup(
                WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(WgrajSamoloty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(WgrajLoty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(WgrajKlientów, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(510, Short.MAX_VALUE))
        );
        WgrajDanePanelLayout.setVerticalGroup(
                WgrajDanePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WgrajDanePanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(WgrajLoty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WgrajSamoloty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WgrajKlientów)
                                .addContainerGap(309, Short.MAX_VALUE))
        );

        RezerwacjaLotuPanel.setRequestFocusEnabled(false);
        RezerwacjaLotuPanel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                RezerwacjaLotuPanelHierarchyChanged(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<Lot> loty = SYSTEM.getLoty();
            public int getSize() { return loty.size(); }
            public String getElementAt(int i) { return (loty.get(i).getLotnisko_p().getNazwa() + " -> " + loty.get(i).getLotnisko_k().getNazwa());  }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Miejsce wylotu");

        jLabel3.setText("Miejsce przylotu");

        obieStrony.setText("W obie strony");
        obieStrony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obieStronyActionPerformed(evt);
            }
        });

        jednaStrona.setText("W jedną stronę");
        jednaStrona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jednaStronaActionPerformed(evt);
            }
        });

        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        jLabel4.setText("Data wylotu");

        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Data przylotu");

        jLabel6.setText("Pasażerowie");

        gowno.setText("jTextField1");

        javax.swing.GroupLayout RezerwacjaLotuPanelLayout = new javax.swing.GroupLayout(RezerwacjaLotuPanel);
        RezerwacjaLotuPanel.setLayout(RezerwacjaLotuPanelLayout);
        RezerwacjaLotuPanelLayout.setHorizontalGroup(
                RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                .addComponent(obieStrony, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jednaStrona)
                                                .addGap(121, 121, 121)
                                                .addComponent(gowno, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3)
                                                        .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                .addGap(10, 10, 10)
                                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(0, 18, Short.MAX_VALUE))
                                                        .addComponent(jSpinner1))))
                                .addContainerGap())
        );
        RezerwacjaLotuPanelLayout.setVerticalGroup(
                RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RezerwacjaLotuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(obieStrony)
                                        .addComponent(jednaStrona)
                                        .addComponent(gowno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(choice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(RezerwacjaLotuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(D)
                                                .addComponent(D2)
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KlientWyborPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(StworzOsobaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StworzFirmaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(RezerwacjaLotuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(WgrajDanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(7, 7, 7)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KlientWyborPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StworzOsobaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StworzFirmaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(RezerwacjaLotuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(WgrajDanePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
        );

        pack();
    }// </editor-fold>

    private void stworzKontoActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void zarezerwujLotActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu.setVisible(false);
        RezerwacjaLotuPanel.setVisible(true);
    }

    private void wgrajDaneActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu.setVisible(false);
        WgrajDanePanel.setVisible(true);
    }

    private void MainMenuHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void KlientWyborPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void wyborFirmaActionPerformed(java.awt.event.ActionEvent evt) {
        KlientWyborPanel.setVisible(false);
        StworzFirmaPanel.setVisible(true);
    }

    private void wyborOsobaActionPerformed(java.awt.event.ActionEvent evt) {
        KlientWyborPanel.setVisible(false);
        StworzOsobaPanel.setVisible(true);
    }

    private void StworzOsobaPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void getImieActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {
        getImie.setText("Imie");
        getNazwisko.setText("Nazwisko");
        SYSTEM.StworzOsobe(getImie.getText(),getNazwisko.getText());
        StworzOsobaPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void getFirmaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Register1ActionPerformed(java.awt.event.ActionEvent evt) {
        getFirma.setText("Firma XYZ");
        getKRS.setText("Numer KRS");
        SYSTEM.StworzFirme(getFirma.getText(),getKRS.getText());
        StworzFirmaPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void StworzFirmaPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {
        KlientWyborPanel.setVisible(false);
        MainMenu.setVisible(true);
    }

    private void goBack1ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzOsobaPanel.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void goBack2ActionPerformed(java.awt.event.ActionEvent evt) {
        StworzFirmaPanel.setVisible(false);
        KlientWyborPanel.setVisible(true);
    }

    private void RezerwacjaLotuPanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void obieStronyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jednaStronaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void WgrajDanePanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {
        // TODO add your handling code here:
    }

    private void WgrajSamolotyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void WgrajLotyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField D;
    private javax.swing.JTextField D2;
    private javax.swing.JPanel KlientWyborPanel;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton Register;
    private javax.swing.JButton Register1;
    private javax.swing.JPanel RezerwacjaLotuPanel;
    private javax.swing.JPanel StworzFirmaPanel;
    private javax.swing.JPanel StworzOsobaPanel;
    private javax.swing.JPanel WgrajDanePanel;
    private javax.swing.JButton WgrajKlientów;
    private javax.swing.JButton WgrajLoty;
    private javax.swing.JButton WgrajSamoloty;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.TextField getFirma;
    private java.awt.TextField getImie;
    private java.awt.TextField getKRS;
    private java.awt.TextField getNazwisko;
    private javax.swing.JButton goBack;
    private javax.swing.JButton goBack1;
    private javax.swing.JButton goBack2;
    private javax.swing.JTextField gowno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JCheckBox jednaStrona;
    private javax.swing.JCheckBox obieStrony;
    private javax.swing.JButton stworzKonto;
    private javax.swing.JButton wgrajDane;
    private javax.swing.JButton wyborFirma;
    private javax.swing.JButton wyborOsoba;
    private javax.swing.JButton zarezerwujLot;
    // End of variables declaration
}
